#!/usr/bin/env bash
set -euo pipefail

: "${ASTRA_DB_ID:?Missing ASTRA_DB_ID}"
: "${ASTRA_REGION:?Missing ASTRA_REGION}"
: "${ASTRA_TOKEN:?Missing ASTRA_TOKEN}"
: "${ASTRA_KEYSPACE:?Missing ASTRA_KEYSPACE}"

BASE_URL="https://${ASTRA_DB_ID}-${ASTRA_REGION}.apps.astra.datastax.com"
CQL_URL="${BASE_URL}/api/rest/v2/cql?keyspace=${ASTRA_KEYSPACE}"

OUT_DIR="${1:-snapshots/latest}"
mkdir -p "${OUT_DIR}"

echo "=========================================="
echo "Generate Schema Snapshot (latest, repo-owned tables only)"
echo "Keyspace : ${ASTRA_KEYSPACE}"
echo "Out Dir  : ${OUT_DIR}"
echo "=========================================="

cql_exec () {
  local cql="$1"
  curl --fail-with-body -sS -X POST "${CQL_URL}" \
    -H "X-Cassandra-Token: ${ASTRA_TOKEN}" \
    -H "Content-Type: text/plain" \
    --data "${cql}"
}

# Determine tables from repo folder names under ./schema
if [ ! -d "schema" ]; then
  echo "No ./schema directory found. Nothing to snapshot."
  exit 0
fi

mapfile -t TABLES < <(find schema -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)

if [ ${#TABLES[@]} -eq 0 ]; then
  echo "No table folders found under ./schema. Expected schema/<tableName>/..."
  exit 0
fi

echo "Repo-owned tables to snapshot:"
printf ' - %s\n' "${TABLES[@]}"

# Fetch indexes once (filter per table)
indexes_json="$(cql_exec "SELECT table_name, index_name, kind, options FROM system_schema.indexes WHERE keyspace_name='${ASTRA_KEYSPACE}';")"

for table in "${TABLES[@]}"; do
  out_file="${OUT_DIR}/${table}.cql"
  echo "------------------------------------------"
  echo "Snapshot table: ${table}"
  echo "Output file   : ${out_file}"

  # Confirm table exists in the environment; if not, create a readable warning snapshot file
  exists_json="$(cql_exec "SELECT table_name FROM system_schema.tables WHERE keyspace_name='${ASTRA_KEYSPACE}' AND table_name='${table}';")"
  if ! echo "$exists_json" | jq -e '.data | length > 0' >/dev/null 2>&1; then
    {
      echo "-- Auto-generated schema snapshot (latest)"
      echo "-- Keyspace: ${ASTRA_KEYSPACE}"
      echo "-- Table: ${table}"
      echo "-- WARNING: Table does not exist in this environment."
      echo "-- This repo contains schema scripts for this table, but it has not been applied yet."
    } > "${out_file}"
    echo "WARN: ${table} does not exist in ${ASTRA_KEYSPACE}. Wrote warning snapshot."
    continue
  fi

  cols_json="$(cql_exec "SELECT column_name, type, kind, position FROM system_schema.columns WHERE keyspace_name='${ASTRA_KEYSPACE}' AND table_name='${table}';")"

  column_lines="$(echo "$cols_json" | jq -r '
    .data
    | (map(select(.kind=="partition_key")) | sort_by(.position))
      + (map(select(.kind=="clustering"))     | sort_by(.position))
      + (map(select(.kind=="static"))         | sort_by(.column_name))
      + (map(select(.kind=="regular"))        | sort_by(.column_name))
    | map("  \(.column_name) \(.type)")
    | join(",\n")
  ')"

  partition_keys="$(echo "$cols_json" | jq -r '
    .data | map(select(.kind=="partition_key")) | sort_by(.position) | map(.column_name) | join(",")
  ')"
  clustering_keys="$(echo "$cols_json" | jq -r '
    .data | map(select(.kind=="clustering")) | sort_by(.position) | map(.column_name) | join(",")
  ')"

  if [ -z "${partition_keys}" ]; then
    {
      echo "-- Auto-generated schema snapshot (latest)"
      echo "-- Keyspace: ${ASTRA_KEYSPACE}"
      echo "-- Table: ${table}"
      echo "-- ERROR: Could not determine partition key from system_schema.columns."
    } > "${out_file}"
    echo "ERROR: No partition key found for ${table}. Wrote error snapshot."
    continue
  fi

  if [ -n "${clustering_keys}" ]; then
    pk_clause="PRIMARY KEY ((${partition_keys}), ${clustering_keys})"
  else
    pk_clause="PRIMARY KEY ((${partition_keys}))"
  fi

  index_block="$(echo "$indexes_json" | jq -r --arg t "$table" '
    .data
    | map(select(.table_name==$t))
    | if length==0 then "" else
        (
          "-- Indexes\n"
          + (map(
              "-- index_name: \(.index_name), kind: \(.kind), options: \(.options|tostring)"
            ) | join("\n"))
        )
      end
  ')"

  {
    echo "-- Auto-generated schema snapshot (latest)"
    echo "-- Keyspace: ${ASTRA_KEYSPACE}"
    echo "-- Table: ${table}"
    echo "-- Generated by CI pipeline (curl + Stargate REST CQL)"
    echo ""
    echo "CREATE TABLE IF NOT EXISTS ${table} ("
    echo "${column_lines},"
    echo "  ${pk_clause}"
    echo ");"
    if [ -n "${index_block}" ]; then
      echo ""
      echo "${index_block}"
    fi
  } > "${out_file}"

  echo "Done: ${out_file}"
done

echo "=========================================="
echo "Snapshot generation completed."
echo "Snapshot folder: ${OUT_DIR}"
echo "=========================================="
