#!/usr/bin/env bash
set -euo pipefail

: "${ASTRA_DB_ID:?Missing ASTRA_DB_ID}"
: "${ASTRA_REGION:?Missing ASTRA_REGION}"
: "${ASTRA_TOKEN:?Missing ASTRA_TOKEN}"
: "${ASTRA_KEYSPACE:?Missing ASTRA_KEYSPACE}"

BASE_URL="https://${ASTRA_DB_ID}-${ASTRA_REGION}.apps.astra.datastax.com"
CQL_URL="${BASE_URL}/api/rest/v2/cql?keyspace=${ASTRA_KEYSPACE}"

OUT_DIR="${1:-snapshots/latest}"
mkdir -p "${OUT_DIR}"

echo "=========================================="
echo "Generate Schema Snapshot (latest)"
echo "Base URL : ${BASE_URL}"
echo "Keyspace : ${ASTRA_KEYSPACE}"
echo "Out Dir  : ${OUT_DIR}"
echo "=========================================="

cql_exec () {
  local cql="$1"
  curl --fail-with-body -sS -X POST "${CQL_URL}" \
    -H "X-Cassandra-Token: ${ASTRA_TOKEN}" \
    -H "Content-Type: text/plain" \
    --data "${cql}"
}

# Get all table names in the keyspace (exclude schema_versions)
tables_json="$(cql_exec "SELECT table_name FROM system_schema.tables WHERE keyspace_name='${ASTRA_KEYSPACE}';")"
mapfile -t TABLES < <(echo "$tables_json" | jq -r '.data[].table_name' | sort | grep -v '^schema_versions$' || true)

if [ ${#TABLES[@]} -eq 0 ]; then
  echo "No tables found in keyspace ${ASTRA_KEYSPACE} (or only schema_versions). Nothing to snapshot."
  exit 0
fi

echo "Tables to snapshot:"
printf ' - %s\n' "${TABLES[@]}"

# Fetch indexes once (filter per table later)
indexes_json="$(cql_exec "SELECT table_name, index_name, kind, options FROM system_schema.indexes WHERE keyspace_name='${ASTRA_KEYSPACE}';")"

for table in "${TABLES[@]}"; do
  out_file="${OUT_DIR}/${table}.cql"
  echo "------------------------------------------"
  echo "Snapshot table: ${table}"
  echo "Output file   : ${out_file}"

  cols_json="$(cql_exec "SELECT column_name, type, kind, position FROM system_schema.columns WHERE keyspace_name='${ASTRA_KEYSPACE}' AND table_name='${table}';")"

  # Build ordered column lines:
  # partition_key + clustering (by position), then static/regular (by name)
  column_lines="$(echo "$cols_json" | jq -r '
    .data
    | (map(select(.kind=="partition_key")) | sort_by(.position))
      + (map(select(.kind=="clustering"))     | sort_by(.position))
      + (map(select(.kind=="static"))         | sort_by(.column_name))
      + (map(select(.kind=="regular"))        | sort_by(.column_name))
    | map("  \(.column_name) \(.type)")
    | join(",\n")
  ')"

  partition_keys="$(echo "$cols_json" | jq -r '
    .data | map(select(.kind=="partition_key")) | sort_by(.position) | map(.column_name) | join(",")
  ')"
  clustering_keys="$(echo "$cols_json" | jq -r '
    .data | map(select(.kind=="clustering")) | sort_by(.position) | map(.column_name) | join(",")
  ')"

  if [ -z "${partition_keys}" ]; then
    echo "WARN: No partition key found for ${table}. Skipping snapshot (unexpected for a table)."
    continue
  fi

  if [ -n "${clustering_keys}" ]; then
    pk_clause="PRIMARY KEY ((${partition_keys}), ${clustering_keys})"
  else
    pk_clause="PRIMARY KEY ((${partition_keys}))"
  fi

  # Best-effort index info as comments
  index_block="$(echo "$indexes_json" | jq -r --arg t "$table" '
    .data
    | map(select(.table_name==$t))
    | if length==0 then "" else
        (
          "-- Indexes\n"
          + (map(
              "-- index_name: \(.index_name), kind: \(.kind), options: \(.options|tostring)"
            ) | join("\n"))
        )
      end
  ')"

  {
    echo "-- Auto-generated schema snapshot (latest)"
    echo "-- Keyspace: ${ASTRA_KEYSPACE}"
    echo "-- Table: ${table}"
    echo "-- Generated by GitHub Actions (curl + Stargate REST CQL)"
    echo ""
    echo "CREATE TABLE IF NOT EXISTS ${table} ("
    echo "${column_lines},"
    echo "  ${pk_clause}"
    echo ");"
    if [ -n "${index_block}" ]; then
      echo ""
      echo "${index_block}"
    fi
  } > "${out_file}"

  echo "Done: ${out_file}"
done

echo "=========================================="
echo "Snapshot generation completed."
echo "Snapshot folder: ${OUT_DIR}"
echo "=========================================="
